### ISSUE TITLE
k6_protobuff_demo seems doesn't work

### ISSUE THREAD

**Issue by RoySunnySean007** [sparrowjack/k6_protobuff_demo#1]
Dear @sparrowjack ,

I found K6 ws doesn't support send binary data(https://k6.io/docs/javascript-api/k6-ws/socket/socket-send-data), my websocket server only receive binary message.
How did u make it via ur demo script? Does ur websocket server receive string message?

Thanks,
Roy

**Comment by sparrowu93** [comment]
I will check that later. Since I had not put this demo into further research

**Comment by 4nif** [comment]
Do you have an update for this issue @sparrowjack?
How do you use protobuf for both side (client and server)?

**Comment by sparrowu93** [comment]
> Do you have an update for this issue @sparrowjack?

I just found that k6 is supposed to support protobuf  in beta at `v0.29.0`. check this out **https://k6.io/docs/javascript-api/k6-net-grpc**
> How do you use protobuf for both side (client and server)?

For server side protobuf just widely support various backend languages, you can find intro at this link [protobuf_tutorials](https://developers.google.com/protocol-buffers/docs/tutorials)

Hope that helps

**Comment by sparrowu93** [comment]
Since protobuf had been supported by official release version, it's strong recommended that to follow the official approach to reach your goal.

If this repo had brought you any confusion, sorry for the misleading and hope you had a good day.
